project:
  type: book

execute:
  freeze: auto

book:
  title: "NUH Analyst BOK"
  author: "NUH Data Analysts"
  date: today
  chapters:
    - index.qmd
    - part: "Resources"
      chapters: 
      - physical_books.qmd
      - e_books.qmd
      - videos.qmd
    - acknowledgements.qmd
    - references.qmd

bibliography: references.bib

format:
  html:
    theme:
      - cosmo
      - brand
    link-external-icon: true
    link-external-newwindow: true
  pdf:
    documentclass: scrreprt



