---
number-sections: false
---

# Glossary

The NHS (National Health Service) can be an alphabet soup of three-letter-acronyms.  This page covers some of the main acronyms used in this book. There is also a helpful [Jargon Buster maintained by the NHS Confederation](https://www.nhsconfed.org/publications/acronym-buster).

## A

### A&G
Advice and Guidance  
A quick-reaction clinical questions process designed to avoid unnecessary referrals from primary care by responding quickly to medical queries about referral options for a patient.

### ABCD
Activity, Bottleneck, Capacity, Demand.  
A common mental model used to describe demand and capacity measurement.  

### ALOS
Average Length of Stay  
See also [LOS](glossary.qmd#los).  LOS is the preferred term at NUH.  

## B

### BAF
Board Assurance Framework

### BOK
Body of Knowledge

## C

### CDC
Community Diagnostic Centre

### CRG
Clinical Reference Group

### CSU
Commissioning Support Unit  
An organisation that provides commissioners with external support, specialist 
skills and knowledge to support them in their role. There are currently 4 CSUs:  
NHS North of England CSU;
NHS Arden and Greater East Midlands CSU;
NHS Midlands and Lancashire CSU;
NHS South, Central and West CSU;

### CT
Computed Tomography   
An important diagnostic imaging process, and one of the 15 diagnostic modalities measured in the DM01 performance dataset.

## D

### DM01
A performance dataset related to the main diagnostic test modalities

### DNA  
Did Not Attend  
The patient did not arrive for a scheduled appointment.  
See also [WNB](glossary.qmd#wnb) 

### DTA
Decision To Admit  
This is a timing point, often in ED, when the decision to admit a patient to hospital as an inpatient is made.
The following timing point will be "admission".  The time between these timing points is monitored as a performance metric.

## E

### ECG
Electrocardiogram  
One of the 15 diagnostic modalities measured in the DM01 performance dataset

### EL
Elective  

### EPMA  
Electronic Prescribing and Medicines Administration

### EPR
Electronic Patient Records System

## F

### FDS
Faster Diagnosis Standard  
A cancer performance measure, measuring the length of time from urgent referral to ruling out or diagnosis of cancer. The performance standard is 28 days.  

### FDS
First Diagnostic Scan  
A timing point within diagnostic pathway tracking

### FTE
Full-time Equivalent  
See also [WTE](glossary.qmd#wte)

## G
## H

## HED
[Healthcare Evaluation Data](https://www.hed.nhs.uk/Info/hed-system.htm)  
HED is a subscription-based online benchmarking solution developed by University Hospitals Birmingham NHS Foundation Trust.

### HES
[Hospital Episode Statistics](https://digital.nhs.uk/data-and-information/data-tools-and-services/data-services/hospital-episode-statistics)  
HES is a curated data product containing details about admissions, 
outpatient appointments and historical accident and emergency attendances at NHS hospitals in England.

### HVLC
High Volume Low Complexity

## I

### ICB
Integrated Care Board

### ICD10
[International statistical classification of diseases and related health problems](https://classbrowser.nhs.uk/#/book/ICD-10-5TH-Edition)  
See also [OPCS4](glossary.qmd#opcs4)

### IP
Inpatient

## J
## K
## L

### LOS
Length of Stay  
See also [ALOS](glossary.qmd#alos).  LOS is the preferred term at NUH.  

## M

### MBRRACE
Maternal and Babies-Reducing Risk through Audits and Confidential Enquiries

### MDC
Making Data Count  
A data-literacy initiative led by NHSE to increase the use of Statistical Process Control techniques in hospital measurement and management processes.  

### MFFD
Medically Fit For Discharge  
See also [MSFT](glossary.qmd#msft)

### MRI
Magnetic Resonance Imaging  
An important diagnostic imaging process, and one of the 15 diagnostic modalities measured in the DM01 performance dataset.

### MSFT
Medically Safe for Transfer  
See also [MFFD](glossary.qmd#mffd)

## N

### NEL
Non-Elective  
See also [UEC](glossary.qmd#uec)

### NEWS
National Early Warning Score

### NHP
New Hospitals Programme

### NHS
National Health Service

### NICU
Neonatal Intensive Care Unit  
See also [NNU](glossary.qmd#nnu)

### NNU
Neonatal Unit  
See also [NICU](glossary.qmd#nicu)

### NOF
NHS Oversight Framework  
Introduced in June 2025, the NOF describes a consistent and transparent approach to assessing 
integrated care boards (ICBs) and NHS trusts, ensuring public accountability for performance 
and providing a foundation for how NHS England works with systems and providers to support improvement.

## O

### OP
Outpatient

### OPCS4
[OPCS Classification of Interventions and Procedures](https://classbrowser.nhs.uk/#/book/OPCS-4.10)  
See also [ICD10](glossary.qmd#icd10)

### OPPROC
Outpatient procedure

## P

### PACS
Picture Archiving and Communication System

### PAS
Patient Administration System

### Pathology
The pathology lab is responsible for testing samples (e.g. blood, urine, fluids, biopsies) to support the diagnosis of patients.

### PCN
Primary Care Network

### PEWS
Pediatric Early Warning Score

### PIFU
Patient-Initiated Follow Up

### Plain Film
Standard X-ray image taken without contrast agents (e.g. dyes or barium)

### PLCM
Patient Level Contract Monitoring  
PLCM is a means to enable the interchange, in a uniform format, of monthly 
patient-level contract monitoring data between commissioners and providers of healthcare.

### POC
Point Of Care

### POD
[Point of Delivery](https://www.datadictionary.nhs.uk/attributes/point_of_delivery_code.html)  
POD is the location where an activity, event or item is provided to a patient.

### PTL
Patient Tracking List

## Q
## R

### R
A statistical programming language used by data analysts and data scientists

### RIS
Radiology Information System

### RTL
Referral Tracking List

### RTT
Referral to Treatment

## S

### SDEC
Same-Day Emergency Care

### SITREP
Situation Report

### SOP
Standard Operating Procedure

### SPC
Statistical Process Control

### SUS+
[Secondary Uses Service](https://digital.nhs.uk/services/secondary-uses-service-sus)
SUS+ is a comprehensive repository for commissioning data sets in England. It is 
held by NHS England and it enables a range of reporting and analyses to support 
the NHS in the delivery of healthcare services.

## T

### TOC
Tranasfer of Care

### TTO
To Take Out  
A drugs prescription that the patient takes away on the day they are discharged from inpatient care.

## U

### UEC
Urgent and Emergency Care

### US
Ultrasound  
A diagnostic imaging process.  Non-obstetric ultrasound is one of the 15 diagnostic modalities measured in the DM01 performance dataset.

## V
## W

### WLI
Waiting List Initiative  
Premium-paid working time agreed in order to reduce the size of a waiting list.

### WNB
Was not Brought  
The patient did not attend a scheduled appointment, but is dependent on others to bring them to the appointments (e.g. pediatric or elderly patients).  
See also [DNA](glossary.qmd#dna)

### WTE
Whole-time Equivalent  
See also [FTE](glossary.qmd#fte)

## X

### XmR
A type of Statistical Process Control (SPC) chart

## Y
## Z
