# Physical Books

This is a list of recommended reading.  Intended to capture some of the core
publications which would interest any data analyst, through to more specialised
material focusing on healthcare specifically, or improvement more generally.

## Healthcare

[The Healthcare Data Guide](https://www.amazon.co.uk/Health-Care-Data-Guide-Improvement/dp/0470902582)  
by Provost & Murray  
Designed to help students and professionals build a skill set specific to using data for improvement of healthcare processes and systems.

[An Introduction to Digital Healthcare in the NHS](https://www.amazon.co.uk/Introduction-Digital-Healthcare-NHS-Third/dp/1399926845)  
by Gary McAllister  
This short book is for professionals working within Healthcare IT, particularly in the NHS. As an introduction, this book is well suited to those who are considering changing careers and working in the Healthcare IT sector. The book aims to provide the reader with a summary of Healthcare IT in the NHS, covering patient flows, healthcare IT systems and modules, healthcare governance, some politics and finally a view of the future.

[Principles of Health Interoperability](https://www.amazon.co.uk/Principles-Health-Interoperability-Information-Technology/dp/3030568822)  
by Tim Benson & Grahame Grieve  
Healthcare is communication. Interoperability can provide information when and where required, facilitate quicker and more soundly based decision-making, reduce waste by cutting out repeated work and improve safety with fewer errors. Interoperability is essential in healthcare, which depends on teamwork and communication.  

## Analysis

[SQL for Data Scientists](https://www.amazon.co.uk/SQL-Data-Scientists-Beginners-Building/dp/1119669367)  
by Renee M.P.Teate  
A resource that’s dedicated to the Structured Query Language (SQL) and dataset design skills that data scientists use most. Aspiring data scientists will learn how to how to construct datasets for exploration, analysis, and machine learning. 

## Visualisation

[The Visual Display of Quantitative Information](https://www.amazon.co.uk/Visual-Display-Quantitative-Information/dp/0961392142)  
by Edward R.Tufte  
"Modern data graphics can do much more than simply substitute for small statistical tables. At their best, graphics are instruments for reasoning about quantitative information. Often the most effective way to describe, explore, and summarise a set of numbers - even a very large set - is to look at pictures of those numbers. Furthermore, of all methods for analysing and communicating statistical information, well-designed data graphics are usually the simplest and at the same time the most powerful."

## Statistics

## Data Science

[The StatQuest Illustrated Guide to Machine Learning](https://www.amazon.co.uk/dp/B0BLM4TLPY)  
by Josh Starmer  
Machine Learning is awesome and powerful, but it can also appear incredibly complicated. That’s where The StatQuest Illustrated Guide to Machine Learning comes in. This book takes the machine learning algorithms, no matter how complicated, and breaks them down into small, bite-sized pieces that are easy to understand. Each concept is clearly illustrated to provide you, the reader, with an intuition about how the methods work that goes beyond the equations alone. 

## Data Engineering

[DAMA - DMBOK](https://dama.org/learning-resources/dama-data-management-body-of-knowledge-dmbok)  
Data Management Body of Knowledge  
Today's organisations recognise that managing data is central to their success. They recognise the value of their data and seek to leverage that value. As human capacity to create and exploit data has increased, so too has the need for reliable data management practices.  

[Database Design for Mere Mortals](https://www.amazon.co.uk/Database-Design-Mere-Mortals-Hands/dp/0201752840)  
by Michael J.Hernandez  
Whatever relational database systems you use, Hernandez will help you design databases that are robust and trustworthy. Never designed a database before? Settling for inadequate generic designs? Running existing databases that need improvement? Start here.

## Improvement

[Business Dynamics - Systems Thinking and Modelling for a Complex World](https://www.amazon.co.uk/Business-Dynamics-Systems-Thinking-Modeling/dp/007238915X)  
by John D. Sterman  
Systems Dynamics is an approach to the study of complexity. Originally developed at the Massachusetts Institute of Technology by Jay Forrester, system dynamics is a unique method devised to help managers and public policymakers design and implement high leverage policies for sustainable success.  

## Manufacturing Improvement

[Out of the Crisis](https://www.amazon.co.uk/Out-Crisis-Press-Edwards-Deming/dp/0262541157)  
by W. Edwards Deming  
Originally published in 1982, Deming offers a theory of management based on his famous 14 Points for Management. "Long-term commitment to new learning and new philosophy is required of any management that seeks transformation. The timid and the fainthearted, and the people that expect quick results, are doomed to disappointment."

[Toyota Production System - Beyond Large-Scale Production](https://www.amazon.co.uk/Toyota-Production-System-Beyond-Large-Scale/dp/0915299143)  
by Taiichi Ohno  
"The Toyota Production System evolved out of need.  Certain restrictions in the marketplace required the production of small quantities of many varieties under conditions of low demand, a fate the Japanese automobile industry had faced in the postwar period."  
"The most important objective of the Toyota Production System has been to increase production efficiency by consistently and thoroughly eliminating waste."

[A Study of the Toyota Production System from and Industrial Engineering Viewpoint](https://www.amazon.co.uk/Study-Toyota-Production-System-Engineering/dp/0915299178)  
by Shigeo Shingo  
"The Toyota Production System has been compared to squeezing water from a dry towel. What this means is that it is a system for thorough waste elimination. Here, waste refers to everything not serving to advance the process, everything that does not increase added value. Many people settle for eliminating the waste that everyone recognises as waste. But much remains that simply has not yet been recognised as waste or that people are willing to tolerate."